version: '3'

services:
    tasks:
        build: ./tasks-service/
        environment:
            - FLASK_APP=service_app:create_app
            - FLASK_ENV=development
            - FLASK_RUN_PORT=8000
        command: flask run --host=0.0.0.0 --no-reload

    expenses:
        build: ./expenses-service/
        environment:
            - FLASK_APP=service_app:create_app
            - FLASK_ENV=development
            - FLASK_RUN_PORT=8000
        command: flask run --host=0.0.0.0 --no-reload

    gateway:
        depends_on: 
            - tasks
            - expenses
        build: ./api-gateway-service/
        environment:
            - FLASK_APP=service_app:create_app
            - FLASK_ENV=development
            - FLASK_RUN_PORT=8000
        ports:
            - 8000:8000
        command: flask run --host=0.0.0.0 --no-reload