version: '3'

services:
    tasks:
        build: ./tasks-service/
        environment:
            - FLASK_APP=service_app:create_app
            - FLASK_ENV=development
            - FLASK_RUN_PORT=8000
        command: gunicorn --bind 0.0.0.0:8000 wsgi

    expenses:
        build: ./expenses-service/
        environment:
            - FLASK_APP=service_app:create_app
            - FLASK_ENV=development
            - FLASK_RUN_PORT=8000
        command: gunicorn --bind 0.0.0.0:8000 wsgi

    gateway:
        depends_on: 
            - tasks
            - expenses
        build: ./api-gateway-service/
        environment:
            - FLASK_APP=service_app:create_app
            - FLASK_ENV=development
            - FLASK_RUN_PORT=8000
        command: gunicorn --bind 0.0.0.0:8000 wsgi
    nginx-server:
        depends_on:
            - gateway
        build: ./nginx-server
        tty: true
        ports:
            - 8000:8000
