from os import getenv


TASKS_SERVICE_HOST = getenv('TASKS_SERVICE_HOST', '127.0.0.1')
TASKS_SERVICE_PORT = getenv('TASKS_SERVICE_PORT', '8888')
TASKS_SERVICE_URL = 'http://{}:{}'.format(TASKS_SERVICE_HOST, TASKS_SERVICE_PORT)

EXPENSES_SERVICE_HOST = getenv('EXPENSES_SERVICE_HOST', '127.0.0.1')
EXPENSES_SERVICE_PORT = getenv('EXPENSES_SERVICE_PORT', '7777')
EXPENSES_SERVICE_URL = 'http://{}:{}'.format(EXPENSES_SERVICE_HOST, EXPENSES_SERVICE_PORT)